# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 4893E051-35D8-42B9-8ECB-9852309BF955;cosmopolitan;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import;
# Disable with : `mulle-sourcetree mark cosmopolitan no-link`
# Disable for this platform: `mulle-sourcetree mark cosmopolitan no-cmake-platform-${MULLE_UNAME}`
#
if( NOT COSMOPOLITAN_LIBRARY)
   find_library( COSMOPOLITAN_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}cosmopolitan${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX} ${CMAKE_STATIC_LIBRARY_PREFIX}cosmopolitan${CMAKE_STATIC_LIBRARY_SUFFIX} cosmopolitan NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "COSMOPOLITAN_LIBRARY is ${COSMOPOLITAN_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( COSMOPOLITAN_LIBRARY)
      #
      # Add COSMOPOLITAN_LIBRARY to DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark cosmopolitan no-cmake-add`
      #
      set( DEPENDENCY_LIBRARIES
         ${DEPENDENCY_LIBRARIES}
         ${COSMOPOLITAN_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark cosmopolitan no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_COSMOPOLITAN_ROOT "${COSMOPOLITAN_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_COSMOPOLITAN_ROOT "${_TMP_COSMOPOLITAN_ROOT}" DIRECTORY)
      #
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark cosmopolitan no-cmake-dependency`
      #
      foreach( _TMP_COSMOPOLITAN_NAME "cosmopolitan")
         set( _TMP_COSMOPOLITAN_DIR "${_TMP_COSMOPOLITAN_ROOT}/include/${_TMP_COSMOPOLITAN_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_COSMOPOLITAN_DIR}/DependenciesAndLibraries.cmake")
            unset( COSMOPOLITAN_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_COSMOPOLITAN_DIR}")
            # we only want top level INHERIT_OBJC_LOADERS, so disable them
            if( NOT NO_INHERIT_OBJC_LOADERS)
               set( NO_INHERIT_OBJC_LOADERS OFF)
            endif()
            list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
            set( NO_INHERIT_OBJC_LOADERS ON)
            #
            include( "${_TMP_COSMOPOLITAN_DIR}/DependenciesAndLibraries.cmake")
            #
            list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
            list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_COSMOPOLITAN_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${COSMOPOLITAN_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_COSMOPOLITAN_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
   else()
      # Disable with: `mulle-sourcetree mark cosmopolitan no-require-link`
      message( FATAL_ERROR "COSMOPOLITAN_LIBRARY was not found")
   endif()
endif()
