/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _demo_c_include_h__
#define _demo_c_include_h__

// You can tweak the following #include with these commands.
// (Use 9735A1A3-F703-4A44-B070-E51169D20327 instead of mulle-fprintf if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-fprintf no-header`
//    rename:              `mulle-sde dependency|library set mulle-fprintf include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-fprintf <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-fprintf [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-fprintf [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-fprintf [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-fprintf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-fprintf/mulle-fprintf.h>   // mulle-fprintf

// You can tweak the following #include with these commands.
// (Use 24D6B628-91A4-4186-895D-567A862F8BF6 instead of mulle-objc-runtime if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-objc-runtime no-header`
//    rename:              `mulle-sde dependency|library set mulle-objc-runtime include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-objc-runtime <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-objc-runtime [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-objc-runtime [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-objc-runtime [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-objc-runtime no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-objc-runtime/mulle-objc-runtime.h>   // mulle-objc-runtime

#endif
