#ifndef demo_objc_include_h__
#define demo_objc_include_h__

/* This is a central include file to keep dependencies out of the library
   C files. It is usally included by .h files only.

   The advantage is that now .c and .h files become motile. They can
   be moved to other projects and don't need to be edited. Also less typing...

   Therefore it is important that this file is called "include.h" and
   not "demo-objc-include.h" to keep the #include statements in the
   library code uniform.

   The C-compiler will pick up the nearest one.
*/

/* Include the header file automatically generated by mulle-sourcetree-to-c.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#include "_demo-objc-include.h"

#ifndef DEMO_OBJC_GLOBAL
# ifdef DEMO_OBJC_BUILD
#  define DEMO_OBJC_GLOBAL    MULLE_C_GLOBAL
# else
#  if defined( DEMO_OBJC_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( DEMO_OBJC_INCLUDE_STATIC))
#   define DEMO_OBJC_GLOBAL   MULLE_C_GLOBAL
#  else
#   define DEMO_OBJC_GLOBAL   extern
#  endif
# endif
#endif

/* You can add some more include statements here */

#include "demo-objc-version.h"

#endif


/*
 * extension : mulle-c/c
 * directory : project-oneshot/executable
 * template  : .../include.h
 * Suppress this comment with `export MULLE_SDE_GENERATE_FILE_COMMENTS=NO`
 */
